include "#!./gradlew -q printConveyorConfig"
include "conveyor-local.conf"

app {
    fsname = alchitry-tester
    long-fsname = alchitry-tester
    vendor = Alchitry
    display-name = Alchitry Tester
    vcs-url = github.com/alchitry/Alchitry-Tester
    license = "GPL-3.0-only"
    description = "Test various Alchitry boards"
    contact-email = "support@alchitry.com"
    rdns-name = com.alchitry.tester
    file-associations = [ .alp ]

    icons = "icons/icon.svg"

    machines = [windows.amd64, linux.amd64.glibc, mac.amd64, mac.aarch64]

    linux {
        root-inputs += install/99-alchitry.rules -> /etc/udev/rules.d/99-alchitry.rules
        symlinks += ${app.linux.prefix}/bin/alchitry -> ${app.linux.install-path}/bin/alchitry

        desktop-file."Desktop Entry".Categories = "GTK;Development"

        amd64.inputs += {
            from = "includes/linux-x64"
            to = "/"
        }
    }

    windows.amd64.inputs += {
        from = "includes/windows-x64"
        to = "/"
    }

    mac {
        deltas = 0 // TODO: Remove when conveyor bug fixed

        info-plist {
            LSMinimumSystemVersion = 13.0
        }

        amd64.inputs += {
            from = "includes/darwin-x64"
            to = "/"
        }

        aarch64.inputs += {
            from = "includes/darwin-arm64"
            to = "/"
        }
    }

    jvm {
        cli {
            alchitry {
                main-class = com.alchitry.labs2.CLIKt
            }
        }
    }

    site {
        github {
            // oauth-token = ${env.GITHUB_TOKEN} // set in conveyor-local.conf
            pages-branch = "gh-pages"
        }
    }
}

conveyor.compatibility-level = 12
//app.site.consistency-checks = warn